# Generated by Django 4.1.7 on 2023-03-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_index_together_remove_category_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='firma',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='images/no_image.jpg', upload_to='images/'),
        ),
    ]
