# Generated by Django 4.1.7 on 2023-03-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_firma_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_all',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
