# Generated by Django 4.1.7 on 2023-04-01 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_product_is_ordered_alter_orderitem_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
