# Generated by Django 4.1.7 on 2023-02-24 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_email_verify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email_verify',
        ),
    ]
