# Generated by Django 4.1.7 on 2023-03-14 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_customuser_is_seller_customuser_seller_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='seller',
            new_name='is_seller',
        ),
    ]
